#!/usr/bin/env python
"""Regenerate the recurring-projection parity fixture.

    cd backend && python scripts/gen_recurring_projection_fixture.py

Writes `frontend/src/components/recurring/__tests__/projection.fixture.json`:
the dates `generate_dates` produces for every case in
`scripts/recurring_projection_cases.py`, pinned to that module's TODAY.

Run it after changing anything in the cadence expansion (`_occurs_on`,
`_phase_anchor`, `_daily_anchor`, `generate_dates`) or after adding a case.
`tests/test_recurring_projection_fixture.py` fails if you forget, and
`projectionParity.test.js` then tells you whether the frontend mirror still
agrees with the new answers.
"""
import json
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
BACKEND = os.path.dirname(HERE)
sys.path.insert(0, BACKEND)

# generate_dates is pure date maths, but importing the router pulls `database.db`
# in, which builds the engine at import time and fails closed without these.
# Defaults rather than overrides, so a real environment keeps its own values —
# and nothing here ever opens a connection, let alone writes.
#
# A FILE url, not `sqlite://`: the in-memory dialect uses SingletonThreadPool,
# which rejects the `max_overflow` db.py passes. The file is never created,
# because no query runs.
os.environ.setdefault(
    "DATABASE_URL",
    "sqlite:///" + os.path.join(tempfile.gettempdir(), "bb-fixture-gen-unused.db"),
)
os.environ.setdefault("JWT_SECRET", "fixture-generation-only")

from scripts.recurring_projection_cases import (  # noqa: E402
    CASES, TODAY, backend_projection,
)

FIXTURE = os.path.join(
    BACKEND, os.pardir, "frontend", "src", "components", "recurring",
    "__tests__", "projection.fixture.json",
)


def build():
    dates = backend_projection()
    return {
        "_comment": (
            "GENERATED by backend/scripts/gen_recurring_projection_fixture.py — "
            "do not hand-edit. These are the dates the BACKEND's generate_dates "
            "produces; projectionParity.test.js asserts the frontend mirror "
            "agrees. Regenerate after changing the cadence rules."
        ),
        "today": TODAY.isoformat(),
        "cases": [
            {"name": name, "why": why, "weeks_ahead": weeks,
             "rule": {k: (v.isoformat() if hasattr(v, "isoformat") else v)
                      for k, v in fields.items()},
             "dates": dates[name]}
            for name, fields, weeks, why in CASES
        ],
    }


if __name__ == "__main__":
    payload = build()
    with open(os.path.normpath(FIXTURE), "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2)
        fh.write("\n")
    total = sum(len(c["dates"]) for c in payload["cases"])
    print(f"wrote {len(payload['cases'])} cases / {total} dates to "
          f"{os.path.normpath(FIXTURE)}")
