/**
 * `computeUpcoming` against the BACKEND's answers, not against itself.
 *
 * This is the check `helpers.test.js` structurally cannot be. That file asserts
 * the mirror produces the dates its author expected; this one asserts it
 * produces the dates `generate_dates` actually produces, for a table of rules
 * the two sides share. The difference is not academic — for as long as the
 * self-check was the only check, four divergences accumulated unnoticed, every
 * one of them visible to the owner as a visit the screen promised and nothing
 * created, or a visit nothing showed and the backend made anyway:
 *
 *   monthly_31    the backend clamps `day_of_month` to the month's last day;
 *                 the mirror rolled the date into the next month and rejected
 *                 it, so a monthly-on-the-31st series showed NO visit in any
 *                 month shorter than 31 days — about five a year.
 *   ends_on_date  `series_end_date` is an exclusive bound. The mirror never
 *                 read the column, so an ended or count-limited series went on
 *                 projecting visits forever.
 *   future_start  `series_start_date` is an inclusive FLOOR, which is how a
 *                 "this and all future visits" split hands over. The mirror
 *                 used it only as a phase anchor, so it showed occurrences
 *                 before the split point — dates the predecessor owns.
 *   short_window  nothing clamps the window on the backend. The mirror floored
 *                 it at 4 weeks, and `EditSeriesModal`'s input allows `min="1"`
 *                 with no backend validation, so a series set to generate 2
 *                 weeks ahead projected 4.
 *
 * ## How the loop closes
 *
 * `projection.fixture.json` is generated by
 * `backend/scripts/gen_recurring_projection_fixture.py` from the real
 * `generate_dates`. `backend/tests/test_recurring_projection_fixture.py` fails
 * if the committed fixture stops matching the backend, so the rules cannot
 * change while these answers are stale; this test then fails if the mirror
 * disagrees with the new answers. Neither half is useful alone — a fixture with
 * no backend check is a snapshot that rots, and a backend check with no
 * frontend comparison proves nothing about the mirror.
 *
 * ## The one divergence left, on purpose
 *
 * `generate_dates` reads `business_today()` (America/New_York); this reads the
 * viewer's local midnight. They agree for an office in Maine and can differ by
 * a day for a viewer elsewhere. It cannot be closed from the browser, which is
 * why both sides are pinned to a fixed date here rather than papered over — and
 * why the standing recommendation is to have the server return the projection
 * and delete the mirror.
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { computeUpcoming } from '../helpers'

const FIXTURE = JSON.parse(readFileSync(
  join(dirname(fileURLToPath(import.meta.url)), 'projection.fixture.json'), 'utf8'))

/** The fixture's pinned date, as LOCAL midnight — what `computeUpcoming` reads. */
function pinClock(iso) {
  const [y, m, d] = iso.split('-').map(Number)
  vi.useFakeTimers()
  vi.setSystemTime(new Date(y, m - 1, d))
}

beforeEach(() => pinClock(FIXTURE.today))
afterEach(() => vi.useRealTimers())

describe('computeUpcoming matches the backend projection', () => {
  it('reads a fixture with real content, so an empty one cannot pass silently', () => {
    // The ratchet failure this guards: an unreadable or truncated fixture would
    // make the loop below run zero assertions and the suite go green.
    expect(FIXTURE.cases.length).toBeGreaterThan(15)
    expect(FIXTURE.cases.reduce((n, c) => n + c.dates.length, 0)).toBeGreaterThan(100)
    expect(FIXTURE.today).toMatch(/^\d{4}-\d{2}-\d{2}$/)
  })

  for (const { name, why, rule, weeks_ahead: weeks, dates } of FIXTURE.cases) {
    it(`${name} — ${why}`, () => {
      // maxCount high enough to compare the whole list: the cap is a display
      // concern and capping here would hide a disagreement past the 8th date.
      const got = computeUpcoming({ ...rule, generate_weeks_ahead: weeks }, [], 999)
      expect(got.map(x => x.date)).toEqual(dates)
    })
  }
})
